services:
  evolution-api:
    container_name: lab_evolution_api
    image: evoapicloud/evolution-api:latest
    restart: always
    ports:
      - 8080:8080
    volumes:
      - evolution_instances:/lab_evolution/instances
    env_file:
      - .env
    depends_on:
      - redis
      - postgres

  postgres:
    container_name: postgres
    image: postgres:15
    command: ["postgres", "-c", "max_connections=1000"]
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432

  redis:
    image: redis:latest
    container_name: redis
    command: >
      redis-server --port 6379 --appendonly yes
    volumes:
      - redis:/data
    ports:
      - 6379:6379

  bot:
    build: .
    container_name: bot
    restart: always
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - evolution-api
      - redis
    volumes:
      - ./vectorstore_data:/app/vectorstore
      - ./rag_files:/app/rag_files
      - ./log:/app/log

volumes:
  evolution_store:
  evolution_instances:
  postgres_data:
  redis:
  vectorstore_data:
  rag_files:
